export enum UnunuraIdentifier {
  Padding = 'p',
  PaddingExtended = 'padding',
  Margin = 'm',
  MarginExtended = 'm',
  Height = 'h',
  HeightExtended = 'height',
  Width = 'w',
  WidthExtended = 'width',
  Border = 'b',
  BorderExtended = 'border',
  Outline = 'o',
  OutlineExtended = 'outline',
  Text = 'text',
  TextFont = 'font',
  Background = 'bg',
  BackgroundExtended = 'background',
  Flexbox = 'f',
  FlexboxExtended = 'flex',
  Grid = 'g',
  GridExtended = 'grid',
  Position = 'pos',
  PositionExtended = 'position',
  Scroll = 'sc',
  ScrollExtended = 'scroll',
  Shadow = 'sh',
  ShadowExtended = 'shadow',
  Rounded = 'r',
  RoundedExtended = 'rounded',
  ZIndex = 'z',
  ZIndexExtended = 'zindex',
  Display = 'd',
  DisplayExtended = 'display',
  Float = 'fl',
  FloatExtended = 'float',
  Transition = 'tr',
  TransitionExtended = 'transition',
  Transform = 'tf',
  TransformExtended = 'transform',
  Typography = 'typo',
  TypographyExtended = 'typography',
  Filter = 'fi',
  FilterExtended = 'filter',
  Style = 'st',
  StyleExtended = 'style',
  Gradient = 'gr',
  GradientExtended = 'gradient',
  Animation = 'an',
  AnimationExtended = 'animation',
  Collection = 'cl',
  CollectionExtended = 'collection',
  Reset = 'reset'
}

export enum UnunuraGlobals {
  None = '?',
  Important = '!',
}

export enum UnunuraKeys {
  MultipleContextOpen = '[',
  MultipleContextClose = ']',
  SpecificContextOpen = '(',
  SpecificContextClose = ')',
  UniqueContext = ':',
}
