// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside.vue')['default']
    AsideCategory: typeof import('./src/components/AsideCategory.vue')['default']
    AsideItem: typeof import('./src/components/AsideItem.vue')['default']
    AsideLogo: typeof import('./src/components/AsideLogo.vue')['default']
    IconArrow: typeof import('./src/components/icon/IconArrow.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MdDocsConcepts: typeof import('./src/components/md/MdDocsConcepts.md')['default']
    MdDocsContexts: typeof import('./src/components/md/MdDocsContexts.md')['default']
    MdDocsGlobals: typeof import('./src/components/md/MdDocsGlobals.md')['default']
    MdDocsIdentifiers: typeof import('./src/components/md/MdDocsIdentifiers.md')['default']
    MdDocsInstall: typeof import('./src/components/md/MdDocsInstall.md')['default']
    MdDocsOptions: typeof import('./src/components/md/MdDocsOptions.md')['default']
    MdDocsSupporters: typeof import('./src/components/md/MdDocsSupporters.md')['default']
    MdDocsWhy: typeof import('./src/components/md/MdDocsWhy.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VueIdentifiersList: typeof import('./src/components/identifiers/VueIdentifiersList.vue')['default']
  }
}
